apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: autoscaling-subscriber-java
  namespace: default
spec:
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_CLEAR_SOURCE: "true"
      FUNC_NAME: dev.openfunction.samples.OpenFunctionImpl
    shipwright:
      params:
        - name: CACHE_IMAGE
          value: openfunctiondev/java-sample-cache:v2
    srcRepo:
      revision: main
      url: https://github.com/OpenFunction/java-samples.git
  image: openfunctiondev/autoscaling-subscriber-java:v2
  imageCredentials:
    name: push-secret
  serving:
    hooks:
      post:
        - dev.openfunction.samples.hooks.ExampleHook
      pre:
        - dev.openfunction.samples.hooks.ExampleHook
    pubsub:
      kafka-server:
        metadata:
          - name: brokers
            value: kafka-server-kafka-brokers:9092
          - name: authRequired
            value: "false"
          - name: allowedTopics
            value: sample-topic
          - name: consumerID
            value: autoscaling-subscriber
        type: pubsub.kafka
        version: v1
    scaleOptions:
      keda:
        scaledObject:
          advanced:
            horizontalPodAutoscalerConfig:
              behavior:
                scaleDown:
                  policies:
                    - periodSeconds: 15
                      type: Percent
                      value: 50
                  stabilizationWindowSeconds: 45
                scaleUp:
                  stabilizationWindowSeconds: 0
          cooldownPeriod: 60
          pollingInterval: 15
        triggers:
          - metadata:
              bootstrapServers: kafka-server-kafka-brokers.default.svc.cluster.local:9092
              consumerGroup: autoscaling-subscriber
              lagThreshold: "20"
              topic: sample-topic
            type: kafka
      maxReplicas: 10
      minReplicas: 0
    template:
      containers:
        - imagePullPolicy: IfNotPresent
          name: function
    triggers:
      dapr:
        - name: kafka-server
          topic: sample-topic
          type: pubsub.kafka
    workloadType: Deployment
  version: v2.0.0
