apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: function-front
  namespace: default
spec:
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_CLEAR_SOURCE: "true"
      FUNC_NAME: dev.openfunction.samples.OpenFunctionImpl
    shipwright:
      params:
        - name: CACHE_IMAGE
          value: openfunctiondev/java-sample-cache:v2
    srcRepo:
      revision: main
      url: https://github.com/OpenFunction/java-samples.git
  image: openfunctiondev/sample-knative-dapr-java:v2
  imageCredentials:
    name: push-secret
  serving:
    bindings:
      kafka-server:
        metadata:
          - name: brokers
            value: kafka-server-kafka-brokers:9092
          - name: authRequired
            value: "false"
          - name: publishTopic
            value: sample-topic
          - name: topics
            value: sample-topic
          - name: consumerGroup
            value: function-front
        type: bindings.kafka
        version: v1
    hooks:
      post:
        - dev.openfunction.samples.hooks.ExampleHook
      pre:
        - dev.openfunction.samples.hooks.ExampleHook
    outputs:
      - dapr:
          name: kafka-server
          operation: create
          type: bindings.kafka
    scaleOptions:
      maxReplicas: 5
      minReplicas: 0
    template:
      containers:
        - imagePullPolicy: IfNotPresent
          name: function
  version: v1.0.0
