apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: get-config-from-file
  namespace: default
spec:
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_CLEAR_SOURCE: "true"
      FUNC_NAME: dev.openfunction.samples.ConfigurationFromFile
    shipwright:
      params:
        - name: CACHE_IMAGE
          value: openfunctiondev/java-sample-cache:v2
    srcRepo:
      revision: main
      url: https://github.com/OpenFunction/java-samples.git
  image: openfunctiondev/get-config-from-file:v2
  imageCredentials:
    name: push-secret
  serving:
    template:
      containers:
        - imagePullPolicy: IfNotPresent
          name: function
          volumeMounts:
            - mountPath: /etc/openfunction/
              name: config
      volumes:
        - configMap:
            defaultMode: 420
            name: get-config-from-file
          name: config
  version: v2.0.0
