apiVersion: v1
kind: ServiceAccount
metadata:
  name: get-config-from-configmap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-config-from-configmap-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-config-from-configmap-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-config-from-configmap-role
subjects:
  - kind: ServiceAccount
    name: get-config-from-configmap
    namespace: default
---
apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: get-config-from-configmap
spec:
  version: "v1.0.0"
  image: "openfunctiondev/get-config-from-configmap:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_NAME: "dev.openfunction.samples.ConfigurationFromConfigmap"
      FUNC_CLEAR_SOURCE: "true"
    srcRepo:
      url: "https://github.com/OpenFunction/java-samples.git"
      revision: "main"
  serving:
    params:
      CONFIGMAP_NAMESPACE: default
      CONFIGMAP_NAME: get-config-from-configmap
      CONFIGMAP_KEY: "config.yaml"
    template:
      serviceAccountName: get-config-from-configmap
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
    runtime: "knative"