apiVersion: v1
kind: ServiceAccount
metadata:
  name: get-config-from-configmap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-config-from-configmap-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-config-from-configmap-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-config-from-configmap-role
subjects:
  - kind: ServiceAccount
    name: get-config-from-configmap
    namespace: default
---
apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: get-config-from-configmap
  namespace: default
spec:
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_CLEAR_SOURCE: "true"
      FUNC_NAME: dev.openfunction.samples.ConfigurationFromConfigmap
    shipwright:
      params:
        - name: CACHE_IMAGE
          value: openfunctiondev/java-sample-cache:v2
    srcRepo:
      revision: main
      url: https://github.com/OpenFunction/java-samples.git
  image: openfunctiondev/get-config-from-configmap:v2
  imageCredentials:
    name: push-secret
  serving:
    params:
      CONFIGMAP_KEY: config.yaml
      CONFIGMAP_NAME: get-config-from-configmap
      CONFIGMAP_NAMESPACE: default
    template:
      containers:
        - imagePullPolicy: IfNotPresent
          name: function
      serviceAccountName: get-config-from-configmap
  version: v2.0.0
