apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: mysql-to-redis
  namespace: default
spec:
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_CLEAR_SOURCE: "true"
      FUNC_NAME: dev.openfunction.samples.MysqlToRedis
    shipwright:
      params:
        - name: CACHE_IMAGE
          value: openfunctiondev/java-sample-cache:v2
    srcRepo:
      revision: main
      url: https://github.com/OpenFunction/java-samples.git
  image: openfunctiondev/mysql-to-redis:v2
  imageCredentials:
    name: push-secret
  serving:
    bindings:
      cron:
        metadata:
          - name: schedule
            value: '@every 5s'
        type: bindings.cron
        version: v1
    params:
      JDBC_DRIVER: com.mysql.cj.jdbc.Driver
      MYSQL_PASSWORD: "123456"
      MYSQL_TABLE: openfunction.states
      MYSQL_URL: jdbc:mysql://mysql:3306/?useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USER: root
      PRIMARY_KEY: key
    states:
      redis:
        spec:
          metadata:
            - name: redisHost
              value: redis:6379
            - name: redisPassword
              value: ""
            - name: keyPrefix
              value: appid
          type: state.redis
          version: v1
    template:
      containers:
        - imagePullPolicy: Always
          name: function
    triggers:
      dapr:
        - name: cron
          type: bindings.cron
  version: v2.0.0
