apiVersion: core.openfunction.io/v1beta2
kind: Function
metadata:
  name: mysql-state-store
  namespace: default
spec:
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_CLEAR_SOURCE: "true"
      FUNC_NAME: dev.openfunction.samples.StateStore
    shipwright:
      params:
        - name: CACHE_IMAGE
          value: openfunctiondev/java-sample-cache:v2
    srcRepo:
      revision: main
      url: https://github.com/OpenFunction/java-samples.git
  image: openfunctiondev/mysql-state-store:v2
  imageCredentials:
    name: push-secret
  serving:
    states:
      mysql:
        spec:
          metadata:
            - name: connectionString
              value: mysql:123456@tcp(mysql:3306)/?allowNativePasswords=true
            - name: schemaName
              value: dapr_state_store
            - name: tableName
              value: state
            - name: timeoutInSeconds
              value: "30"
            - name: keyPrefix
              value: appid
          type: state.mysql
          version: v1
    template:
      containers:
        - imagePullPolicy: IfNotPresent
          name: function
  version: v2.0.0
