apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: mysql-to-redis
spec:
  version: "v1.0.0"
  image: "openfunctiondev/mysql-to-redis:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: openfunction/builder-java:v2-18
    env:
      FUNC_NAME: "dev.openfunction.samples.MysqlToRedis"
      FUNC_CLEAR_SOURCE: "true"
      FUNCTION_FRAMEWORK_VERSION: "1.1.0-SNAPSHOT"
      MAVEN_REPOSITORY: "https://s01.oss.sonatype.org/content/repositories/snapshots/"
    srcRepo:
      url: "https://github.com/OpenFunction/java-samples.git"
      revision: "main"
  serving:
    params:
      REDIS_STATE_STORE_NAME: "redis-state-store"
      JDBC_DRIVER: "com.mysql.cj.jdbc.Driver"
      MYSQL_URL: "jdbc:mysql://mysql:3306/?useSSL=false&allowPublicKeyRetrieval=true"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_TABLE: "openfunction.states"
      PRIMARY_KEY: "key"
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: Always
    runtime: "async"
    inputs:
      - name: cron
        component: cron
    bindings:
      cron:
        type: bindings.cron
        version: v1
        metadata:
          - name: schedule
            value: "@every 5s"

