kind: Deployment
apiVersion: apps/v1
metadata:
  name: async-function
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: async-function
  template:
    metadata:
      labels:
        app.kubernetes.io/name: async-function
    spec:
      containers:
        - name: nocalhost-dev
          image: 'nocalhost-docker.pkg.coding.net/nocalhost/dev-images/java:11'
          command:
            - /bin/sh
            - '-c'
            - tail -f /dev/null
          workingDir: /home/nocalhost-dev
          ports:
            - name: function-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              value: default
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
